apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector: 
    matchLabels:
      component:  web
  template:
    metadata:
      labels:
        component:  web
        visualize:  "true"
    spec:
      containers:
        - name: client
          image: dockeruser1212/mvc
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "API_URL"
            value: "http://restapi.default.svc.cluster.local:3051/api/values"
            

---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    component:  web
