apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector: 
    matchLabels:
      component:  redis
  template:
    metadata:
      labels:
        component:  redis
        visualize:  "true"
    spec:
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    component: redis
