apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
spec:
  replicas: 1
  selector: 
    matchLabels:
      component:  restapi
  template:
    metadata:
      labels:
        component:  restapi
    spec:
      containers:
        - name: restapi
          image: dockeruser1212/restapi
          ports:
          - containerPort: 80



        
