apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector: 
    matchLabels:
      component:  web
  template:
    metadata:
      labels:
        component:  web
        visualize:  "true"
    spec:
      containers:
        - name: web
          image: dockeruser1212/mvc
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "API_URL"
            value: "http://restapi:3051/api/values"
            

